### ISSUE TITLE
User Registration Implementation

### ISSUE THREAD

**Issue by martjellino** [martjellino/vortexa-first-task#3]
Create user registration functionality, including sign-up form, user database, and authentication.

**Task**

- [x]  Design user registration form.
- [x]  Set up user database.
- [x]  Implement user authentication.

**Comment by indrazm** [comment]
We might able to improve this as following : 

- [x] Create Login UI Form
- [x] Create Register UI Form
- [x] Create handleLoginFunction in lib folder
- [x] Create handleRegisterFunction in lib folder

And then we assign to the team. I do add labels as enhancement also.
